apiVersion: v1
kind: Service
metadata:
  name: real-estate-redis
spec:
  selector:
    app: real-estate-redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  type: ClusterIP 