apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcmVhbC1lc3RhdGUtZGI6NTQzMi9yZWFsX2VzdGF0ZV9kYg==
  username: dXNlcg==
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
type: Opaque
data:
  secret-key: eW91ci1zZWNyZXQta2V5
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
type: Opaque
data:
  redis-url: cmVkaXM6Ly9yZWFsLWVzdGF0ZS1yZWRpczo2Mzc5 